### ISSUE TITLE
Why the switch to vyper?

### ISSUE THREAD

**Issue by WyseNynja** [Uniswap/contracts-vyper#16]
I'm at the start of a project writing some ethereum contracts and I'm wanting to interact with Uniswap. I would love to know what the motivations were for switching from solidity (https://github.com/Uniswap/old-solidity-contracts) to vyper.

**Comment by haydenadams** [comment]
Vyper is awesome - built in overflow/underflow protection, extreme readability, pythonic, some re-entrancy protection, easy testing. The TLDR is that it forces best practices, something severely lacking in the smart contract space. And It only took a few days to port over the entire smart contract from Solidity. The original move was suggested by Vitalik. 

I felt comfortable moving to Vyper since at the time the EF was building Casper in a Vyper contract (Casper is no longer a smart contract). B/c of this, there was a big push from the EF that massively improved the Vyper codebase to the point where it was (mostly) ready for production contracts. I thought Uniswap could be a good project to demonstrate the Vyper's capabilities, and might gain some press as well.

**Comment by BlinkyStitt** [comment]
On a related note, if someone does need to need a solidity version of uniswap, check out https://github.com/PhABC/uniswap-solidity
