### ISSUE TITLE
Can't compile contracts on master branch, are other branch contracts okay to test on local testnet?

### ISSUE THREAD

**Issue by shakeib98** [Uniswap/contracts-vyper#48]
I am making an app that uses uniswap's contract also. So as I was trying to compile and deploy the master branch contracts on local testnet Ganache, I was constantly facing issues in the compilation. I think it's because of the old vyper language syntax. So I compiled other branch contracts and it compiled smoothly. 
I want to ask can I use them for unit testing? Are they okay? Or what other ways are there to compile the old contract?

**Comment by dmilla** [comment]
Hello!

I had the same issue a while ago and upgraded contracts to make them work with latest version at the time. All tests were passing as you can see here #44 . Feel free to use them if needed!

However, since then I've found other, easier ways to solve this issue if you don't need to directly modify Uniswap but just use it within your project. As described [here](https://medium.com/@samajammin/how-to-interact-with-ethereums-mainnet-in-a-development-environment-with-ganache-3d8649df0876), it's possible to have a local testnet with the contracts you need already deployed!

Best regards,
Diego
